include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
  errors:
    avoid_print: warning # Avoid using the print function

linter:
  rules:
    - prefer_single_quotes # Use single quotes instead of double quotes